### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2861164410** [Nwflower/auto-plugin#1]
![Screenshot_20221225_215845](https://user-images.githubusercontent.com/118712290/209470957-184047f6-3900-43bc-8399-d3ccc919d64e.jpg)
载入报错

**Comment by Nwflower** [comment]
该报错不是自动化插件的报错。自动化插件是所有插件中第二个运行的插件（仅次于Atlas），你已成功加载了抽卡插件和其他插件，必然也已经加载了自动化插件。
此处的Auto可能是依赖名称，望周知。
