### ISSUE TITLE
自动更新群名片

### ISSUE THREAD

**Issue by OMGLogic** [Nwflower/auto-plugin#18]
自动更新群名片模块，有些模块例如微博热搜不想要，直接删除文件后台会报错，请问应该怎么操作只保留需要的模块。

**Comment by OMGLogic** [comment]
报错提示如下
![image](https://user-images.githubusercontent.com/67633987/231675354-aa1bffa0-9b99-4467-8397-47cb39293ca7.png)

**Comment by Nwflower** [comment]
使用指令：#切换名片样式 切换到你需要的名片模块后，再删除用不上的模块即可
