### ISSUE TITLE
任务表命令报错

### ISSUE THREAD

**Issue by AllureLove98** [Nwflower/auto-plugin#19]
麻烦大佬看一下

0|Yunzai-Bot  | [YzBot][23:53:58.224][MARK] [自动化插件_指令表][autoJobs][私聊][开朗的网友()] #任务表
0|Yunzai-Bot  | [YzBot][23:53:58.225][ERRO] [自动化插件_指令表][autoJobs]
0|Yunzai-Bot  | [YzBot][23:53:58.226][ERRO] TypeError: Cannot read properties of null (reading 'nextInvocation')
0|Yunzai-Bot  |     at file:///root/Yunzai-Bot/plugins/auto-plugin/app/autoCommandHelp.js:72:27
0|Yunzai-Bot  |     at Array.forEach (<anonymous>)
0|Yunzai-Bot  |     at autoCommandHelp.autoJobs (file:///root/Yunzai-Bot/plugins/auto-plugin/app/autoCommandHelp.js:71:17)
0|Yunzai-Bot  |     at PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:273:55)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by 8852690** [comment]
一样的报错

**Comment by Nwflower** [comment]
问题无法复现，无法修复，可能为特定版本Yunzai的兼容性问题

**Comment by 8852690** [comment]
应该是兼容方面的问题，这两天更新之后又恢复正常了
