### ISSUE TITLE
#定时指令 的权限在哪里配置？

### ISSUE THREAD

**Issue by PrussianBlueCN** [Nwflower/auto-plugin#20]
群友使用这一功能会返回你没有权限，读过readme并在仓库内搜索过权限相关内容，没有找到配置权限的地方，请问该如何处理？

**Comment by Nwflower** [comment]
该功能还处于测试中，为了安全暂未向机器人主人以外的身份组开放。目前延时指令已正常开放权限，corn指令由于可能会被利用，corn部分暂不开放。
