### ISSUE TITLE
TRSS云崽下自动化插件运行报错

### ISSUE THREAD

**Issue by SouthernDreamS6** [Nwflower/auto-plugin#21]
23年三月底更新最新版TRSS云崽后自动化插件开始报错（TRSS基于Miao-Yunzai改造）
报错内容如下
![image](https://github.com/Nwflower/auto-plugin/assets/79357465/1cda6a0d-e2d7-4bc3-8435-d58defb93898)

![image](https://github.com/Nwflower/auto-plugin/assets/79357465/7b09f1ed-29b5-45c6-9ce8-d2d474737e90)

![image](https://github.com/Nwflower/auto-plugin/assets/79357465/83bf3e8c-a59e-47fd-b7f6-12c8f781d6bd)

**Comment by Nwflower** [comment]
目前自动化插件暂时无法兼容多账号体系，此问题将定于7月左右修复。
