### ISSUE TITLE
添加新任务后任务表命令报错

### ISSUE THREAD

**Issue by AileYoung233** [Nwflower/auto-plugin#54]
安装自动化插件后，输入【#任务表】，可以返回插件默认的7个任务。
然后通过【#定时指令 -c="0 0 10 ? * SUN" -t="#日历"】添加定时任务后，再使用【#任务表】时报错：
TypeError: Cannot read properties of undefined (reading 'nextInvocation')
截图：
![微信截图_20241116164412](https://github.com/user-attachments/assets/05e7b19c-6566-41f3-845d-fa5aae9faf4a)

也不知道我这个任务到底添加成功没。重启云崽后，再次使用【#任务表】，又返回默认的7个任务

**Comment by AileYoung233** [comment]
添加日志调试后发现，添加#定时指令后，autoCommandHelp.js里，71行循环中，新增的val的值为：
{ name: '自动指令调用-【#日历】', cron: '0 0 12 ? * SUN' }
也就是只有name和cron节点，所以val.job为undefined，导致val.job.nextInvocation报错
![debug1](https://github.com/user-attachments/assets/f194acec-3efe-49f5-aae6-a88958101f88)
![debug2](https://github.com/user-attachments/assets/68b007a5-1fe5-4659-b3a7-a7d9611c9e8f)

观察代码后发现nextInvocation其实就是要获取下一次调用时间，但是调试发现新增的定时指令是取消状态
![debug3](https://github.com/user-attachments/assets/4b966853-03de-4d23-a9ca-46e64af499d3)

**Comment by AileYoung233** [comment]
进一步看代码发现，【#定时指令】添加时，将task进行push时，没有传入job，导致任务实际上是没有创建成功的，应该修改auto-plugin/app/autoCommand.js，在91行左右，将此处创建出来的job对象也push到task列表中，即：
![debug5](https://github.com/user-attachments/assets/1ff60828-9451-4792-b4f0-ac1ae9a9f17b)

经测试，这样任务就能成功创建了，在【#任务表】中，也可以获取下次执行时间，val变量打印出来也能看到job节点了：
![debug6](https://github.com/user-attachments/assets/8c82a353-138d-406d-9684-7fe51d5d38f9)

但是这样的任务只是临时的，yunzai重启后就会失效，而且在那个群创建的任务就只会在哪个群执行，无法指定到另一个群，因此我再想想如何固话任务并指定执行的群号

**Comment by Nwflower** [comment]
你好，本插件已经基本停止维护了，如果有需要，欢迎提pr！

**Comment by Nwflower** [comment]
感谢你对本插件的关注与支持
