### ISSUE TITLE
功能请求：希望能支持群名片分群聊更新

### ISSUE THREAD

**Issue by CUZNIL** [Nwflower/auto-plugin#8]
具体来说就是，希望能不要每次都一秒内把所有群聊的群名片都改了，可以分配到一分钟的几个时间点。
比如我有三个群，cron表达式0/7 0/4 * * * ? *对应执行时间

```
2023-02-27 14:36:00
2023-02-27 14:36:07
2023-02-27 14:36:14
2023-02-27 14:36:21
2023-02-27 14:36:28
```

就希望能第一次更新第一个群，第二次更新第二个群，第三次更新第三个群，第四次更新第一个群这样。

一秒内全部群名片都更新怕QQ犯贱。

**Comment by Nwflower** [comment]
该功能已经上线
