### ISSUE TITLE
icqq似乎无法更新群名片

### ISSUE THREAD

**Issue by CUZNIL** [Nwflower/auto-plugin#9]
目前不少云崽(比如[喵喵云崽](https://gitee.com/yoimiya-kokomi/Yunzai-Bot))已经把登录问题频出的oicq换成了icqq，我也跟着更了。

似乎是在换成icqq后无法更新群名片了。我稍微修改了下原代码来排差原因，最终确认是[autoGroupName](https://github.com/Nwflower/auto-plugin/blob/master/app/autoGroupName.js)的setGroupCard函数出了问题，通过日志可以观察到BOT认为自己已经更改群名片，但是实际没有。具体查证/日志如下：

![Z@_V(J1(6@O}MPEZ4G@L_PY](https://user-images.githubusercontent.com/76582404/223434124-cb93b3a1-c136-4f6b-8eb5-e1606ba7b8a6.png)

如图所示，为了确认问题所在做了一点更改，不会影响插件正常工作。下图是日志。

![IR~CMU0 SPXX0SPBO{O)BXV](https://user-images.githubusercontent.com/76582404/223434256-9eed48c7-3a1a-40d6-a825-53a7e3acc962.jpg)

仔细观察日志的这个部分（见下图），可以发现BOT认为当前群名片是`不吃头发的爱丽丝｜当前系统活力43.30%`，然后尝试更改为`不吃头发的爱丽丝｜当前系统活力42.64%`

![image](https://user-images.githubusercontent.com/76582404/223434414-07dfebb8-a306-48ab-a723-63db71a00597.png)

但是实际上QQ群里看到的群名片始终没有改变，如下图。

![)WM01LFR7YZBHM`_(8K9YDI](https://user-images.githubusercontent.com/76582404/223434885-74869311-2fe3-45e6-957d-41947792b426.png)

**Comment by Nwflower** [comment]
很抱歉，oicq和icqq更新群名片的函数是一致的，且已安装icqq的项目实测也能正常改名片。
很有可能是你的群太多 或者 QQ号在更改群名片方面被风控。
可以尝试手动登录机器人账号更改一下名片看能否更改成功。

**Comment by CUZNIL** [comment]
> 

我手动改名片是成功的，但是BOT确认不到我的修改。不然我全部重装试试吧，之前重装auto也是这样就一直没管。

**Comment by Nwflower** [comment]
请先进入配置文件或使用锅巴插件确认一下更新开关是否打开

**Comment by CUZNIL** [comment]
> 很抱歉，我无法对你提供任何帮助。如果是icqq的问题，或许icqq的作者知道如何让群名片成功更改。

好吧，谢谢。我自己重装试试。我也只是怀疑是不是icqq，毕竟差不多就是更新了icqq才开始更新群名片失效

**Comment by CUZNIL** [comment]
> 很抱歉，我无法对你提供任何帮助。如果是icqq的问题，或许icqq的作者知道如何让群名片成功更改。

我重装以后才发现，改成一次性全更就能你正常工作了，如图

![image](https://user-images.githubusercontent.com/76582404/223467605-2784aeba-dcac-4b35-bb6a-79bbfc9cfa6e.png)

选每次改一个群就会导致`#更新群名片`没有报错并失败

![image](https://user-images.githubusercontent.com/76582404/223467950-e76e4dcb-2082-44a0-85fc-375de177568d.png)

似乎是这个群名片更新模式有问题
